services:
  - type: web
    name: openig-instagram-gateway
    env: node
    plan: free
    region: oregon
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 2895
      - key: HOST
        value: 0.0.0.0
      - key: API_KEY
        generateValue: true
    healthCheckPath: /api/v1/health
